#giorgi maisuradze
#nuca qoridze
#aleqsandre kereselidze
#davit adeishvili
#lasha dekanoidze
#giorgi kupatadze
#atuka khuskivadze
#lizi lomtatidze
#mariam gugeshashvili
#gabriel jobava
#daniel abramiani
#davit narimanidze
#mate beridze
#dachi sazandrishvili
#zuka abashidze
#nika edisherashvili
#nino xvichia
#nika kubaneishvili
#giorgi vanishvili
#mate dolidze
#dimitri muxigulashvili
#ako tchakhnakia
#nikoloz bucxrikidze
#dima bakuradze
#luka akofiani
#gio gagnidze
#guram vakhtangashvili
#sandro zabakhidze